import React from 'react'
import styles from '../style'
const Footer = () => {
  return (
    <div className='flex flex-col bg-[#444444]'>
        <div className='items-center ml-10 align-items'>
            <h2 className='text-white font-mulish font-semibold xs:text-[25px] text-[40px] xs:leading-[76.8px] leading-[66.8px]'>Bike Rentals in Bangalore: Choose Your Two-Wheeled Companion</h2>
            <p className='font-mulish text-dimWhite text-[15px] leading-[25px] w-[1100px]'> Welcome to Royal Brothers, Bangalore's premier bike rental service. Royal Brothers is the first startup to obtain a license to operate bike rentals in Bangalore. Whether you're looking for 2-wheeler rental in Bangalore for a short-term or a long-term lease, we have the perfect ride for you. We offer a wide variety of vehicles starting from scooters such as Activa, Dio, Aprilia SR, TVS Ntorq, Ather, and Aviator to powerful bikes such as Royal Enfield Classic 350, KTM Duke 200, BMW, Yamaha Fazer, etc. With the mission to “Reimagine mobility powered by trust”, our single point of focus has been to provide a seamless customer experience. <br className='top-10'/> Now you can experience a hassle-free and convenient way to rent bikes in Bangalore with our dedicated bike rental app. Available for both Android and iOS devices. Our user-friendly app allows you to effortlessly browse our wide selection of bikes or scooters, choose the perfect ride for your needs, and book it with just a few taps. Skip the queues and paperwork, and enjoy a seamless and efficient rental experience right from your smartphone. Download our bike rental app today and unlock the freedom to explore Bangalore on two wheels at your convenience. </p>
        </div>  
        <div className='items-center ml-10 align-items'>
            <h2 className='text-white font-mulish font-semibold xs:text-[25px] text-[40px] xs:leading-[76.8px] leading-[66.8px]'>Self Drive Bikes in Bangalore for Easy Commute</h2>
            <p className='font-mulish text-dimWhite text-[15px] leading-[25px] w-[1100px]'>
            Bike rentals is a shared mobility offering that allows users to own the vehicle for only the duration of their need and return after it. It is a much better option economically. Users do not have to invest a huge sum of money to buy vehicles and instead spend a small amount as and when they need a two wheeler. Users also need not take the burden of insurance and maintenance. We also provide 24/7 roadside assistance to customers who rent a bike in Bangalore. <br/> In addition to offering bikes for rent online, we also have a range of rental packages to fit your budget and duration of stay. Our daily rental rates are competitive and affordable, and we offer discounts for longer rentals. We also have a range of rental add-ons such as helmet rentals, protective gear, and insurance to ensure your safety and peace of mind. <br/> Two wheelers on rent in Bangalore is a much safer alternative to public transport. Users can travel to places without being dependent on anyone else while also maintaining social distance. Renting self-ride bikes in Bangalore is also a safer alternative in terms of safety to cabs because the user doesn’t share the ride with anyone else. 
            </p>
        </div>
        <div className='items-center ml-10 align-items'>
            <h2 className='text-white font-mulish font-semibold xs:text-[25px] text-[40px] xs:leading-[76.8px] leading-[66.8px]'>Unleash Your Adventurous Spirit with Two Wheeler On Rent in Bangalore</h2>
            <p className='font-mulish text-dimWhite text-[15px] leading-[25px] w-[1100px]'>The use case for motorbikes on rent in Bangalore is many fold. Our customers rent vehicles to run daily errands and commute within the city. We have offerings ranging from a few hours to months (Monthly Bike Rental). A person who is new to the city uses Royal Brothers bike rentals to navigate the city and also house hunting. More powerful two wheeler alternatives such as Royal Enfield Himalayan, Bajaj Avenger, Dominar, etc is used to go on weekend long rides. Bangalore has a lot of tourist attractions nearby (One Day Trips Near Bangalore) which makes it a prime spot to start your weekend getaway through hiring a bike in Bangalore from Royal Brothers. Or you can find here, Top 30 Places to Visit & Best Routes to Ride from Bangalore by opting for a bullet on rent. <br/> If you're in need of a two wheeler for rent in Bangalore, look no further than Royal Brothers. Our team of friendly and knowledgeable staff are available to assist you with anything from choosing the right bike to planning your route. We're dedicated to providing the best bike hire in Bangalore and will do everything we can to ensure your biking adventure is a success. <br/> Our offering also extends to electric bikes for rent in Bangalore to cater to the environmentally cautious users. Such as Yobykes Drift, Pure EV Epluto, etc. We have customers who also use bike rentals in Bangalore to test ride vehicles that they are interested in buying. Booking a weekend trip allows the customers to explore everything that a particular bike has to offer. You can travel solo and travel safely with Royal Brothers.  </p>
        </div>
        <div className='items-center ml-10 align-items'>
            <h2 className='text-white font-mulish font-semibold xs:text-[25px] text-[40px] xs:leading-[76.8px] leading-[66.8px]'>Bike Rental Near to You - Our Bike Stations in Bangalore</h2>
            <p className='font-mulish text-dimWhite text-[15px] leading-[25px] w-[1100px]'>So why wait? Book your ride with Royal Brothers today and experience the freedom and convenience of exploring the city on two wheels. We look forward to helping you plan your perfect biking adventure. So, if you want to rent a bike in Bangalore or any other two-wheeler, we're here to help. Contact us today to learn more about our motorcycle rental in Bangalore and book your ride. <br/> We are present in multiple locations across the city so that our users do not have to travel farther to hire a bike in Bangalore. <br/> Our pick-up points are at: Indiranagar, Koramangala, HSR Layout, HBR Layout, Whitefield, BTM Layout, Banashankari, Yeswanthpur, Marathahalli, Majestic, Bellendur, and Singasandra. </p>
        </div>
    </div>
  )
}

export default Footer